starting documentation

diff --git a/slex b/slex
--- a/slex
+++ b/slex
@@ -1,3 +1,13 @@
+if [ -z "$1" ]; then
+    echo "Usage: slex <path to slex file>"
+    exit 1
+fi
+
+if ! [ -f "$1" ]; then 
+    echo "Error: could not find file $1"
+    exit 1
+fi
+
 if [ -d "./src/main/scala" ]; then
     mkdir -p ./src/main/scala/parsing
     java -jar ~/projects/slex/target/scala-3.3.2/slex.jar $1
